spring.application.name=notification-service
server.port=8082

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=true


spring.threads.virtual.enabled=true

jwt.secret.key = ${JWT_SECRET}

spring.kafka.topic.name=orders
spring.kafka.bootstrap-servers= ${KAFKA_CONSUMER_URL}
spring.kafka.consumer.group-id= orders_group_id_1
spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer= com.ipr.notificationservice.kafka.OrderEventDeserializer
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= com.ipr.notificationservice.kafka.OrderEventSerializer