spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5433/orderdb
spring.datasource.username=user
spring.datasource.password=usersecret
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=true
spring.jpa.hibernate.ddl-auto=none