spring.application.name=order-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/orderdb
spring.datasource.username=user
spring.datasource.password=usersecret

spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=true


spring.threads.virtual.enabled=true